swagger: '2.0'
info:
  version: 2.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Service API
basePath: /
tags:
- name: catalogue
- name: cart
- name: order
- name: user
paths:
  /catalogue:
    get:
      tags:
      - catalogue
      operationId: listCatalogue
      produces:
      - application/json
      parameters:
      - name: page
        in: query
        required: false
        type: integer
        format: int32
      - name: size
        in: query
        required: false
        type: integer
        format: int32
      - name: tags
        in: query
        required: false
        type: string
      - name: sort
        in: query
        required: false
        type: string
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/Sock'
        400: {}
  /catalogue/size:
    get:
      tags:
      - catalogue
      operationId: getCatalogueSize
      produces:
      - application/json
      parameters:
      - name: tags
        in: query
        required: false
        type: string
      responses:
        200:
          schema:
            $ref: '#/definitions/CatalogueSize'
  /catalogue/{id}:
    get:
      tags:
      - catalogue
      operationId: getCatalogueItem
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        200:
          schema:
            $ref: '#/definitions/Sock'
        404: {}
  /tags:
    get:
      tags:
      - catalogue
      operationId: listTags
      produces:
      - application/json
      responses:
        200:
          schema:
            $ref: '#/definitions/Tags'
  /cart:
    get:
      tags:
      - cart
      operationId: getCart
      produces:
      - application/json
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/CartItem'
    post:
      tags:
      - cart
      operationId: addCartItem
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/AddCartItemRequest'
      responses:
        201: {}
        400: {}
        500: {}
    delete:
      tags:
      - cart
      operationId: emptyCart
      responses:
        202: {}
  /cart/update:
    post:
      tags:
      - cart
      operationId: updateCartItem
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/UpdateCartItemRequest'
      responses:
        202: {}
        400: {}
        500: {}
  /cart/{id}:
    delete:
      tags:
      - cart
      operationId: removeCartItem
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        202: {}
        400: {}
  /orders:
    get:
      tags:
      - order
      operationId: listOrders
      produces:
      - application/json
      responses:
        201:
          schema:
            type: array
            items:
              $ref: '#/definitions/Order'
    post:
      tags:
      - order
      operationId: createOrder
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        required: false
        schema:
          $ref: '#/definitions/NewOrderRequest'
      responses:
        201:
          schema:
            $ref: '#/definitions/Order'
        406: {}
        500: {}
  /register:
    post:
      tags:
      - user
      operationId: registerCustomer
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/RegisterRequest'
      responses:
        200:
          schema:
            $ref: '#/definitions/RegisterResponse'
        500: {}
  /login:
    get:
      tags:
      - user
      operationId: login
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: true
        type: string
      responses:
        200: {}
        401: {}
  /customers:
    get:
      tags:
      - user
      operationId: listCustomers
      produces:
      - application/json
      responses:
        200:
          schema:
            type: object
    post:
      tags:
      - user
      operationId: createCustomer
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/RegisterRequest'
      responses:
        200:
          schema:
            $ref: '#/definitions/Customer'
  /customers/{id}:
    get:
      tags:
      - user
      operationId: getCustomer
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        200:
          schema:
            $ref: '#/definitions/Customer'
        404: {}
    delete:
      tags:
      - user
      operationId: deleteCustomer
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        200: {}
        404: {}
  /cards:
    get:
      tags:
      - user
      operationId: listCards
      produces:
      - application/json
      responses:
        200:
          schema:
            type: object
    post:
      tags:
      - user
      operationId: createCard
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/CardRequest'
      responses:
        200:
          schema:
            $ref: '#/definitions/Card'
  /cards/{id}:
    get:
      tags:
      - user
      operationId: getCard
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        200:
          schema:
            $ref: '#/definitions/Card'
        404: {}
    delete:
      tags:
      - user
      operationId: deleteCard
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        200: {}
        404: {}
  /addresses:
    get:
      tags:
      - user
      operationId: listAddresses
      produces:
      - application/json
      responses:
        200:
          schema:
            type: object
    post:
      tags:
      - user
      operationId: createAddress
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/AddressRequest'
      responses:
        200:
          schema:
            $ref: '#/definitions/Address'
  /addresses/{id}:
    delete:
      tags:
      - user
      operationId: deleteAddress
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        200: {}
        404: {}
  /card:
    get:
      tags:
      - user
      operationId: getCurrentCard
      produces:
      - application/json
      responses:
        200:
          schema:
            $ref: '#/definitions/MaskedCard'
  /address:
    get:
      tags:
      - user
      operationId: getCurrentAddress
      produces:
      - application/json
      responses:
        200:
          schema:
            $ref: '#/definitions/Address'
definitions:
  Sock:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      imageUrl:
        type: array
        items:
          type: string
      price:
        type: number
        format: float
      count:
        type: integer
        format: int32
      tag:
        type: array
        items:
          type: string
    required:
    - id
    - name
    - price
  CatalogueSize:
    type: object
    properties:
      size:
        type: integer
        format: int32
    required:
    - size
  Tags:
    type: object
    properties:
      tags:
        type: array
        items:
          type: string
    required:
    - tags
  CartItem:
    type: object
    properties:
      itemId:
        type: string
      quantity:
        type: integer
        format: int32
      unitPrice:
        type: number
        format: float
    required:
    - itemId
    - quantity
  AddCartItemRequest:
    type: object
    properties:
      id:
        type: string
    required:
    - id
  UpdateCartItemRequest:
    type: object
    properties:
      id:
        type: string
      quantity:
        type: integer
        format: int32
    required:
    - id
    - quantity
  NewOrderRequest:
    type: object
    properties:
      customer:
        type: string
      address:
        type: string
      card:
        type: string
      items:
        type: string
  RegisterRequest:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
    required:
    - username
    - password
    - email
    - firstName
    - lastName
  RegisterResponse:
    type: object
    properties:
      id:
        type: string
    required:
    - id
  CardRequest:
    type: object
    properties:
      longNum:
        type: string
      expires:
        type: string
      ccv:
        type: string
    required:
    - longNum
    - expires
    - ccv
  AddressRequest:
    type: object
    properties:
      street:
        type: string
      number:
        type: string
      country:
        type: string
      city:
        type: string
      postcode:
        type: string
    required:
    - street
    - number
    - country
    - city
    - postcode
  Order:
    type: object
    properties:
      id:
        type: string
      customerId:
        type: string
      date:
        type: string
      total:
        type: number
        format: float
      status:
        type: string
    required:
    - id
    - customerId
  Customer:
    type: object
    properties:
      id:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      username:
        type: string
    required:
    - id
    - username
  Card:
    type: object
    properties:
      id:
        type: string
      longNum:
        type: string
      expires:
        type: string
      ccv:
        type: string
    required:
    - id
  MaskedCard:
    type: object
    properties:
      number:
        type: string
    required:
    - number
  Address:
    type: object
    properties:
      id:
        type: string
      number:
        type: string
      street:
        type: string
      city:
        type: string
      postcode:
        type: string
      country:
        type: string
    required:
    - id
