package io.mist.cli.fault;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.PathItem;
import io.swagger.v3.oas.models.media.MediaType;
import io.swagger.v3.oas.models.media.Schema;
import io.swagger.v3.oas.models.responses.ApiResponse;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * UX W3 (REVIEW-UX-RECONCILIATION U8, mist-ux-design.md rev 2 §D2): proposes
 * data-integrity target triples from an OpenAPI spec so a user does not start
 * from a blank registry.
 *
 * <p>Scope is deliberately narrow — CRUD heuristics over the spec:
 * <ul>
 *   <li>write = a POST with a JSON object request body and a 2xx response;</li>
 *   <li>read-back = a GET on the SAME path whose 200 response is
 *       COLLECTION-SHAPED (a bare array, or an object carrying an array
 *       property — the shapes {@code extractItems} can evaluate). Per-entity
 *       {@code GET /res/{id}} read-backs are NEVER proposed: the runtime's
 *       membership check is collection-only and a mis-typed read-back would
 *       yield perpetual false LOST verdicts (U8);</li>
 *   <li>isolation key = required string properties of the request schema
 *       (server-generated {@code id} excluded), most-required-first, max 2.</li>
 * </ul>
 * Bodyless writes, value-delta probes and supplied-isolation cases (the
 * expert tier) are out of heuristic reach BY DESIGN and simply not proposed.
 *
 * <p>The output is a PROPOSAL for human review — written as
 * {@code proposed-triples.yaml}, never auto-loaded as the registry. The
 * {@code dependency} field (a trace-matchable service name) is not derivable
 * from the spec and is emitted as a TODO the user must fill; the in-run
 * quarantine rule ({@link DataIntegrityRuntime#observeTripleHasObservedPresent})
 * additionally protects runtime verdicts against a mis-bound proposal.
 */
public final class TriplesProposer {

    /** One proposed triple with its confidence + reviewer notes. */
    public static final class Proposal {
        public final String name;
        public final String writeEndpoint;
        public final String readbackEndpoint;
        public final List<String> isolationKey;
        public final String confidence; // high | medium
        public final String note;

        Proposal(String name, String writeEndpoint, String readbackEndpoint,
                 List<String> isolationKey, String confidence, String note) {
            this.name = name;
            this.writeEndpoint = writeEndpoint;
            this.readbackEndpoint = readbackEndpoint;
            this.isolationKey = isolationKey;
            this.confidence = confidence;
            this.note = note;
        }
    }

    private TriplesProposer() {
    }

    /** Scans the spec and returns the proposals (pure; unit-testable). */
    public static List<Proposal> propose(OpenAPI api) {
        List<Proposal> out = new ArrayList<>();
        if (api == null || api.getPaths() == null) {
            return out;
        }
        for (Map.Entry<String, PathItem> e : api.getPaths().entrySet()) {
            String path = e.getKey();
            PathItem item = e.getValue();
            if (item == null || item.getPost() == null || item.getGet() == null) {
                continue; // write + same-path read required
            }
            Operation post = item.getPost();
            Operation get = item.getGet();
            if (!hasSuccessResponse(post)) {
                continue;
            }
            Schema<?> reqSchema = resolve(api, jsonSchemaOf(post));
            if (reqSchema == null || reqSchema.getProperties() == null
                    || reqSchema.getProperties().isEmpty()) {
                continue; // bodyless / opaque writes = expert tier, never proposed
            }
            String confidence = collectionShape(api, get);
            if (confidence == null) {
                continue; // U8: only collection-shaped read-backs are evaluable
            }
            List<String> keys = isolationKeys(reqSchema);
            if (keys.isEmpty()) {
                continue; // nothing to freshen/match on
            }
            String name = deriveName(path);
            out.add(new Proposal(name,
                    "POST " + path,
                    "GET " + path,
                    keys,
                    confidence,
                    "same-path collection read-back; verify it is the SYSTEM OF RECORD for the write"));
        }
        return out;
    }

    /** Renders proposals as a reviewable YAML document (proposed-triples.yaml). */
    public static String toYaml(List<Proposal> proposals) {
        StringBuilder sb = new StringBuilder();
        sb.append("# PROPOSED target triples — generated by TriplesProposer (UX W3). REVIEW BEFORE USE.\n");
        sb.append("# This file is a PROPOSAL, not a registry: rename to target-triples.yaml (or point\n");
        sb.append("# mst.oracle.dataintegrity.registry at it) only AFTER you have\n");
        sb.append("#   1. filled every TODO(dependency) with the persisting service's trace name,\n");
        sb.append("#   2. confirmed each read-back is the SYSTEM OF RECORD for its write,\n");
        sb.append("#   3. removed proposals you do not want checked.\n");
        sb.append("# Heuristic scope: body-carrying POST + same-path collection-shaped GET only.\n");
        sb.append("# Bodyless writes / value-delta probes / supplied isolation (the expert tier)\n");
        sb.append("# are NOT proposable — author those by hand (see the data-integrity docs).\n");
        sb.append("# At runtime, a triple whose read-back never shows ANY write landing is\n");
        sb.append("# QUARANTINED (warning, not failure) — the guard for a mis-bound proposal.\n");
        sb.append("triples:\n");
        if (proposals.isEmpty()) {
            sb.append("  # (no body-carrying POST with a same-path collection-shaped GET was found)\n");
        }
        for (Proposal p : proposals) {
            sb.append("  - name: ").append(p.name).append('\n');
            sb.append("    # confidence: ").append(p.confidence).append(" — ").append(p.note).append('\n');
            sb.append("    write_endpoint: \"").append(p.writeEndpoint).append("\"\n");
            sb.append("    dependency: TODO-REVIEW  # TODO(dependency): trace-matchable name of the PERSISTING service\n");
            sb.append("    readback_endpoint: \"").append(p.readbackEndpoint).append("\"\n");
            sb.append("    isolation_key: [").append(String.join(", ", p.isolationKey)).append("]\n");
            sb.append("    isolation_strategy: fresh-strings\n");
        }
        return sb.toString();
    }

    /** CLI: {@code TriplesProposer <openapi-spec> [out-yaml]} (default {@code proposed-triples.yaml}). */
    public static void main(String[] args) throws Exception {
        if (args.length < 1) {
            System.err.println("usage: TriplesProposer <openapi-spec.yaml|json> [out.yaml]");
            System.exit(2);
        }
        OpenAPI api = new io.mist.core.spec.OpenAPISpecification(args[0]).getSpecification();
        List<Proposal> proposals = propose(api);
        java.nio.file.Path out = java.nio.file.Paths.get(args.length > 1 ? args[1] : "proposed-triples.yaml");
        java.nio.file.Files.write(out, toYaml(proposals).getBytes(java.nio.charset.StandardCharsets.UTF_8));
        System.out.println("proposed " + proposals.size() + " triple(s) -> " + out.toAbsolutePath()
                + "  (REVIEW BEFORE USE — fill TODO(dependency), confirm system-of-record)");
    }

    // ── heuristics ──

    private static boolean hasSuccessResponse(Operation op) {
        if (op.getResponses() == null) {
            return false;
        }
        for (String code : op.getResponses().keySet()) {
            if (code.startsWith("2")) {
                return true;
            }
        }
        return false;
    }

    /**
     * Collection-shape check on the GET 200 (U8): "high" for a bare array or
     * an object with a {@code data} array property (the {status,msg,data:[]}
     * envelope), "medium" for an object with any other array property, null
     * when not collection-shaped (per-entity object, primitive, opaque).
     */
    private static String collectionShape(OpenAPI api, Operation get) {
        if (get.getResponses() == null) {
            return null;
        }
        ApiResponse ok = get.getResponses().get("200");
        if (ok == null) {
            return null;
        }
        Schema<?> schema = resolve(api, jsonSchemaOf(ok));
        if (schema == null) {
            return null;
        }
        if ("array".equals(schema.getType())) {
            return "high";
        }
        Map<String, Schema> props = schema.getProperties();
        if (props == null) {
            return null;
        }
        String fallback = null;
        for (Map.Entry<String, Schema> p : props.entrySet()) {
            Schema<?> resolved = resolve(api, p.getValue());
            if (resolved != null && "array".equals(resolved.getType())) {
                if ("data".equals(p.getKey())) {
                    return "high";
                }
                fallback = "medium";
            }
        }
        return fallback;
    }

    /** Required string properties first (excluding server-generated {@code id}), then optional; max 2. */
    private static List<String> isolationKeys(Schema<?> reqSchema) {
        List<String> required = reqSchema.getRequired() == null
                ? java.util.Collections.emptyList() : reqSchema.getRequired();
        Map<String, Schema> props = reqSchema.getProperties() == null
                ? new LinkedHashMap<>() : reqSchema.getProperties();
        List<String> keys = new ArrayList<>();
        for (String name : props.keySet()) {
            if (!required.contains(name)) {
                continue;
            }
            if (isStringProp(props.get(name), name) && keys.size() < 2) {
                keys.add(name);
            }
        }
        if (keys.isEmpty()) {
            for (String name : props.keySet()) {
                if (isStringProp(props.get(name), name) && keys.size() < 2) {
                    keys.add(name);
                }
            }
        }
        return keys;
    }

    private static boolean isStringProp(Schema<?> schema, String name) {
        return schema != null && "string".equals(schema.getType()) && !"id".equals(name);
    }

    private static Schema<?> jsonSchemaOf(Operation post) {
        if (post.getRequestBody() == null || post.getRequestBody().getContent() == null) {
            return null;
        }
        MediaType mt = post.getRequestBody().getContent().get("application/json");
        if (mt == null && !post.getRequestBody().getContent().isEmpty()) {
            mt = post.getRequestBody().getContent().values().iterator().next();
        }
        return mt == null ? null : mt.getSchema();
    }

    private static Schema<?> jsonSchemaOf(ApiResponse response) {
        if (response.getContent() == null) {
            return null;
        }
        MediaType mt = response.getContent().get("application/json");
        if (mt == null && !response.getContent().isEmpty()) {
            mt = response.getContent().values().iterator().next();
        }
        return mt == null ? null : mt.getSchema();
    }

    /** One-level $ref resolution against components/schemas. */
    private static Schema<?> resolve(OpenAPI api, Schema<?> schema) {
        if (schema == null || schema.get$ref() == null) {
            return schema;
        }
        if (api.getComponents() == null || api.getComponents().getSchemas() == null) {
            return null;
        }
        String ref = schema.get$ref();
        String name = ref.substring(ref.lastIndexOf('/') + 1);
        return api.getComponents().getSchemas().get(name);
    }

    private static String deriveName(String path) {
        String[] segs = path.split("/");
        StringBuilder sb = new StringBuilder();
        for (int i = segs.length - 1; i >= 0 && sb.length() < 40; i--) {
            String s = segs[i].replaceAll("[^A-Za-z0-9]", "");
            if (s.isEmpty() || s.matches("v\\d+") || "api".equals(s)) {
                continue;
            }
            if (sb.length() > 0) {
                sb.insert(0, '-');
            }
            sb.insert(0, s.toLowerCase());
            if (sb.length() >= 20) {
                break;
            }
        }
        return (sb.length() == 0 ? "proposed" : sb.toString()) + "-create";
    }
}
