swagger: '2.0'
info:
  version: 2.2.0
  title: Service API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /api
tags:
- name: cart
- name: checkout
- name: product
- name: recommendation
- name: shipping
paths:
  /cart:
    get:
      tags:
      - cart
      operationId: getCart
      produces:
      - application/json
      parameters:
      - name: sessionId
        in: query
        required: false
        type: string
      - name: currencyCode
        in: query
        required: false
        type: string
      responses:
        '200':
          schema:
            $ref: '#/definitions/Cart'
    post:
      tags:
      - cart
      operationId: addCartItem
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/AddItemRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/Cart'
  /checkout:
    post:
      tags:
      - checkout
      operationId: placeOrder
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: currencyCode
        in: query
        required: false
        type: string
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/PlaceOrderRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/OrderResult'
  /products/{id}:
    get:
      tags:
      - product
      operationId: getProduct
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - name: currencyCode
        in: query
        required: false
        type: string
      responses:
        '200':
          schema:
            $ref: '#/definitions/Product'
        '404': {}
  /recommendations:
    get:
      tags:
      - recommendation
      operationId: listRecommendations
      produces:
      - application/json
      parameters:
      - name: productIds
        in: query
        required: false
        type: array
        items:
          type: string
        collectionFormat: multi
      - name: sessionId
        in: query
        required: false
        type: string
      responses:
        '200':
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
  /shipping:
    get:
      tags:
      - shipping
      operationId: getShippingQuote
      produces:
      - application/json
      parameters:
      - name: itemList
        in: query
        required: false
        type: string
      - name: currencyCode
        in: query
        required: false
        type: string
      responses:
        '200':
          schema:
            $ref: '#/definitions/Money'
definitions:
  Money:
    type: object
    properties:
      currencyCode:
        type: string
      units:
        type: integer
        format: int64
      nanos:
        type: integer
        format: int32
  CartItem:
    type: object
    properties:
      productId:
        type: string
      quantity:
        type: integer
        format: int32
    required:
    - productId
    - quantity
  Cart:
    type: object
    properties:
      userId:
        type: string
      items:
        type: array
        items:
          $ref: '#/definitions/CartItem'
  AddItemRequest:
    type: object
    properties:
      userId:
        type: string
      item:
        $ref: '#/definitions/CartItem'
    required:
    - item
  Address:
    type: object
    properties:
      streetAddress:
        type: string
      city:
        type: string
      state:
        type: string
      country:
        type: string
      zipCode:
        type: string
  CreditCardInfo:
    type: object
    properties:
      creditCardNumber:
        type: string
      creditCardCvv:
        type: integer
        format: int32
      creditCardExpirationYear:
        type: integer
        format: int32
      creditCardExpirationMonth:
        type: integer
        format: int32
  PlaceOrderRequest:
    type: object
    properties:
      userId:
        type: string
      userCurrency:
        type: string
      email:
        type: string
      address:
        $ref: '#/definitions/Address'
      creditCard:
        $ref: '#/definitions/CreditCardInfo'
    required:
    - address
    - email
  OrderItem:
    type: object
    properties:
      item:
        $ref: '#/definitions/CartItem'
      cost:
        $ref: '#/definitions/Money'
  OrderResult:
    type: object
    properties:
      orderId:
        type: string
      shippingTrackingId:
        type: string
      shippingCost:
        $ref: '#/definitions/Money'
      shippingAddress:
        $ref: '#/definitions/Address'
      items:
        type: array
        items:
          $ref: '#/definitions/OrderItem'
  Product:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      picture:
        type: string
      priceUsd:
        $ref: '#/definitions/Money'
      categories:
        type: array
        items:
          type: string
    required:
    - id
    - name
