swagger: '2.0'
info:
  version: 1.0.0
  termsOfService: https://istio.io/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Service API
basePath: /api/v1
tags:
- name: product
- name: review
- name: rating
paths:
  /products:
    get:
      tags:
      - product
      operationId: getProducts
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
  /products/{id}:
    get:
      tags:
      - product
      operationId: getProduct
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int32
      responses:
        200:
          schema:
            $ref: '#/definitions/ProductDetails'
        400: {}
  /products/{id}/reviews:
    get:
      tags:
      - review
      operationId: getProductReviews
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int32
      responses:
        200:
          schema:
            $ref: '#/definitions/ProductReviews'
        400: {}
  /products/{id}/ratings:
    get:
      tags:
      - rating
      operationId: getProductRatings
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int32
      responses:
        200:
          schema:
            $ref: '#/definitions/ProductRatings'
        400: {}
definitions:
  Product:
    type: object
    properties:
      id:
        type: integer
        format: int32
      descriptionHtml:
        type: string
    required:
    - id
    - title
    - descriptionHtml
  ProductDetails:
    type: object
    properties:
      id:
        type: integer
        format: int32
      publisher:
        type: string
      language:
        type: string
      author:
        type: string
      ISBN-10:
        type: string
      ISBN-13:
        type: string
      year:
        type: integer
        format: int32
      type:
        type: string
        enum:
        - paperback
        - hardcover
      pages:
        type: integer
        format: int32
    required:
    - id
    - publisher
    - language
    - author
    - ISBN-10
    - ISBN-13
    - year
    - type
    - pages
  ProductReviews:
    type: object
    properties:
      id:
        type: integer
        format: int32
      reviews:
        type: array
        items:
          $ref: '#/definitions/Review'
    required:
    - id
    - reviews
  Review:
    type: object
    properties:
      reviewer:
        type: string
      text:
        type: string
      rating:
        $ref: '#/definitions/Rating'
    required:
    - reviewer
    - text
  Rating:
    type: object
    properties:
      stars:
        type: integer
        format: int32
        minimum: 1
        maximum: 5
      color:
        type: string
        enum:
        - red
        - black
    required:
    - stars
    - color
  ProductRatings:
    type: object
    properties:
      id:
        type: integer
        format: int32
      ratings:
        type: object
        additionalProperties:
          type: string
    required:
    - id
    - ratings
