swagger: '2.0'
info:
  version: 1.4.2
  title: Service API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /
tags:
- name: webui
- name: persistence
paths:
  /tools.descartes.teastore.webui/loginAction:
    post:
      tags:
      - webui
      operationId: loginAction
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - text/html
      parameters:
      - name: username
        in: formData
        required: false
        type: string
      - name: password
        in: formData
        required: false
        type: string
      - name: signin
        in: formData
        required: false
        type: string
      - name: logout
        in: formData
        required: false
        type: string
      - name: referer
        in: formData
        required: false
        type: string
      responses:
        '302': {}
        '200': {}
  /tools.descartes.teastore.webui/cartAction:
    post:
      tags:
      - webui
      operationId: cartAction
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - text/html
      parameters:
      - name: confirm
        in: query
        required: false
        type: string
      - name: addToCart
        in: formData
        required: false
        type: string
      - name: productid
        in: formData
        required: false
        type: integer
        format: int64
      - name: firstname
        in: formData
        required: false
        type: string
      - name: lastname
        in: formData
        required: false
        type: string
      - name: address1
        in: formData
        required: false
        type: string
      - name: address2
        in: formData
        required: false
        type: string
      - name: cardtype
        in: formData
        required: false
        type: string
      - name: cardnumber
        in: formData
        required: false
        type: string
      - name: expirydate
        in: formData
        required: false
        type: string
      responses:
        '302': {}
        '200': {}
  /tools.descartes.teastore.webui/profile:
    get:
      tags:
      - webui
      operationId: getProfile
      produces:
      - text/html
      responses:
        '200': {}
        '302': {}
  /tools.descartes.teastore.persistence/rest/orders:
    get:
      tags:
      - persistence
      operationId: listOrders
      produces:
      - application/json
      parameters:
      - name: start
        in: query
        required: false
        type: integer
        format: int32
      - name: max
        in: query
        required: false
        type: integer
        format: int32
      responses:
        '200':
          schema:
            type: array
            items:
              $ref: '#/definitions/Order'
    post:
      tags:
      - persistence
      operationId: createOrder
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: body
        in: body
        required: false
        schema:
          $ref: '#/definitions/Order'
      responses:
        '200':
          schema:
            $ref: '#/definitions/Order'
        '500': {}
  /tools.descartes.teastore.persistence/rest/orders/user/{uid}:
    get:
      tags:
      - persistence
      operationId: listOrdersForUser
      produces:
      - application/json
      parameters:
      - name: uid
        in: path
        required: true
        type: integer
        format: int64
      responses:
        '200':
          schema:
            type: array
            items:
              $ref: '#/definitions/Order'
  /tools.descartes.teastore.persistence/rest/orderitems/order/{oid}:
    get:
      tags:
      - persistence
      operationId: listOrderItemsForOrder
      produces:
      - application/json
      parameters:
      - name: oid
        in: path
        required: true
        type: integer
        format: int64
      responses:
        '200':
          schema:
            type: array
            items:
              $ref: '#/definitions/OrderItem'
  /tools.descartes.teastore.persistence/rest/products:
    get:
      tags:
      - persistence
      operationId: listProducts
      produces:
      - application/json
      parameters:
      - name: category
        in: query
        required: false
        type: integer
        format: int64
      - name: start
        in: query
        required: false
        type: integer
        format: int32
      - name: max
        in: query
        required: false
        type: integer
        format: int32
      responses:
        '200':
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
  /tools.descartes.teastore.persistence/rest/products/{pid}:
    get:
      tags:
      - persistence
      operationId: getProduct
      produces:
      - application/json
      parameters:
      - name: pid
        in: path
        required: true
        type: integer
        format: int64
      responses:
        '200':
          schema:
            $ref: '#/definitions/Product'
        '404': {}
definitions:
  Order:
    type: object
    properties:
      id:
        type: integer
        format: int64
      userId:
        type: integer
        format: int64
      time:
        type: string
      totalPriceInCents:
        type: integer
        format: int64
      addressName:
        type: string
      address1:
        type: string
      address2:
        type: string
      creditCardCompany:
        type: string
      creditCardNumber:
        type: string
      creditCardExpiryDate:
        type: string
    required:
    - id
    - userId
  OrderItem:
    type: object
    properties:
      id:
        type: integer
        format: int64
      productId:
        type: integer
        format: int64
      orderId:
        type: integer
        format: int64
      quantity:
        type: integer
        format: int32
      unitPriceInCents:
        type: integer
        format: int64
    required:
    - id
    - orderId
    - productId
  Product:
    type: object
    properties:
      id:
        type: integer
        format: int64
      categoryId:
        type: integer
        format: int64
      name:
        type: string
      listPriceInCents:
        type: integer
        format: int64
    required:
    - id
    - name
